### ISSUE TITLE
Default dir configs for sldbLi don't work as expected

### ISSUE THREAD

**Issue by badosu** [Yaribz/SLDB#11]
Received:

```
sldbLi_1        | 20220203153446 - ERROR    - [SldbLi] Configuration file "etc/sldbLi.conf" contains inconsistent values for following global parameter(s): etcDir,varDir,logDir
sldbLi_1        | 20220203153446 - ERROR    - [SldbLi] Unable to load main configuration parameters
sldbLi_1        | 20220203153446 - CRITICAL - [SldbLi] Unable to load SldbLi configuration at startup
```

The default values are empty, replacing with etc, var and log would be helpful: https://github.com/Yaribz/SLDB/blob/master/etc/sldbLi.conf#L19-L21

**Comment by Yaribz** [comment]
Well this is the expected behavior currently, these parameters are supposed to be configured manually when installing SLDB (step 7 of [the installation doc](https://github.com/Yaribz/SLDB#installation) ). Any automatic install procedure has to update this configuration file, ideally using the `updateConfFile.pl` script.

The sldbLi conf file doesn't properly support relative paths btw, as opposed to the SPADS ones. They may seem to work but they are relative to the current working directory when launching the program instead of the SLDB base directory, which may lead to unwanted behaviors in some cases...

**Comment by badosu** [comment]
Thanks, closed as non-applicable
