### ISSUE TITLE
CRITICAL - [slMonitor] Unable to find rank of user x in accounts table!

### ISSUE THREAD

**Issue by rosscosack** [Yaribz/SLDB#7]
slMonitor is crashing with the following msg
```
20200426031532 - CRITICAL - [slMonitor] Unable to find rank of user "356" in accounts table!
```
There is no id 356 in the accounts table, max id in accounts table is currently 355
How can this get out of sync? there are no logs of failed inserts
sldbLi log 
```
20200426064300 - NOTICE   - [SLDB] getSkills called for non-rated user ID "356"
20200426064300 - ERROR    - [SLDB] Unable to find rank of unrated player (id:356, userId:356)
20200426064300 - WARNING  - [SldbLi] Unable to find skill of ID "356" / IP <IP ADDRESS REMOVED> getSkill call from parity
20200426064440 - NOTICE   - [SLDB] getSkills called for non-rated user ID "356"
20200426064440 - ERROR    - [SLDB] Unable to find rank of unrated player (id:356, userId:356)
20200426064440 - WARNING  - [SldbLi] Unable to find skill of ID "356" / IP <IP ADDRESS REMOVED>, getSkill call from parity
20200426081318 - NOTICE   - [SLDB] getSkills called for non-rated user ID "6"
20200426082848 - NOTICE   - [SLDB] getSkills called for non-rated user ID "332"
20200426082848 - ERROR    - [SLDB] Unable to find rank of unrated player (id:332, userId:332)
20200426082848 - WARNING  - [SldbLi] Unable to find skill of ID "332" / IP <IP ADDRESS REMOVED>, getSkill call from parity
20200426111240 - NOTICE   - [SLDB] getSkills called for non-rated user ID "337"
20200426112251 - NOTICE   - [SLDB] getSkills called for non-rated user ID "337"
20200426112346 - NOTICE   - [SLDB] getSkills called for non-rated user ID "337"
```

**Comment by Yaribz** [comment]
I'm afraid it's still a case of inconsistent commands sent by uberserver, but let's take a closer look at what happened here.

First, can you show me the result of following SQL commands on your SLDB database to help understand the current state:

    select max(accountId),max(userId) from userAccounts;
    select max(id) from accounts;

Then, can you perform following steps so that I can find out if your uberserver instance is really sending inconsistent commands:
- add following line in your etc/slMonitor.conf file: "lobbyLogLevel:5"
- stop slMonitor if it is running (either by saying !quit to it in private in lobby or by sending kill signal)
- rename your slMonitor.log file (in var/log/) to something like slMonitor.log.sav
- start slMonitor and reproduce the crash
- stop slMonitor if it's still running somehow
- rename the newly created slMonitor.log file (in var/log/) to slMonitor.log.debug
- rename the original slMonitor.log.sav file to slMonitor.log
- remove the line "lobbyLogLevel:5" that you added in first step from etc/slMonitor.conf file
- start slMonitor
- send me the slMonitor.log.debug file for investigation after your removed sensitive information from it (mainly the "LOGIN" lines which contain your password hash)

**Comment by rosscosack** [comment]
User accounts results
```
select max(accountId),max(userId) from userAccounts; -- 357
select max(id) from accounts; --  355
```
I have buffed the log level as per above and have restarted slMonitor waiting for the next crash

**Comment by rosscosack** [comment]
```
pr 26 20:26:55 road-flag systemd[1]: Started Spads.
Apr 26 20:26:56 road-flag perl[18687]: 20200426202656 - NOTICE   - [SPADS] Initializing SPADS 0.12.6
Apr 26 20:30:51 road-flag perl[18687]: 20200426202656 - NOTICE   - [SPADS] Loading Spring archives using unitsync librar
Apr 26 20:30:51 road-flag perl[18687]: 20200426203051 - WARNING  - [SPADS] Spring archives loading process took 3 minute
Apr 26 20:30:51 road-flag perl[18687]: 20200426203051 - NOTICE   - [SPADS] Spring server mode: dedicated
Apr 26 20:30:51 road-flag perl[18687]: 20200426203051 - NOTICE   - [SimpleEvent] Event loop initialized using internal m
Apr 26 20:30:51 road-flag perl[18687]: 20200426203051 - NOTICE   - [SPADS] <DownloadArchives> Plugin loaded (version 0.3
Apr 26 20:30:51 road-flag perl[18687]: 20200426203051 - NOTICE   - [SimpleEvent] Starting event loop...
20200426193413 - NOTICE   - [SpringLobbyInterface] Connecting to localhost:8200
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "TASSERVER unknown * 8201 0", unmarshalled as:"TASSERVER,unknown,*,8201,0"
20200426193413 - DEBUG    - [SpringLobbyInterface] Sending to lobby server: "LOGIN SpringLobbyMonitor tS/HMzHoJfWRysA019hu2Q== 0 * SpringLobbyMonitor v0.3      0       l t sp cl"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "ACCEPTED SpringLobbyMonitor", unmarshalled as:"ACCEPTED,SpringLobbyMonitor"
20200426193413 - INFO     - [slMonitor] Logged on lobby server
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "MOTD You have successfully logged into Uberserver!", unmarshalled as:"MOTD,You have successfully logged into Uberserver!"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "MOTD ", unmarshalled as:"MOTD"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "MOTD Server version: unknown", unmarshalled as:"MOTD,Server version: unknown"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "MOTD Your client did not use TLS. Your connection is not secure.", unmarshalled as:"MOTD,Your client did not use TLS. Your connection is not secure."
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "MOTD  -- -- - -- --", unmarshalled as:"MOTD, -- -- - -- --"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "ADDUSER ChanServ AU None ChanServ", unmarshalled as:"ADDUSER,ChanServ,AU,None,ChanServ"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "ADDUSER iridium[host] DE 25 SPADS v0.12.6a", unmarshalled as:"ADDUSER,iridium[host],DE,25,SPADS v0.12.6a"
20200426193413 - DEBUG    - [SpringLobbyInterface] Sending to lobby server: "GETUSERID iridium[host]"
20200426193413 - DEBUG    - [SpringLobbyInterface] Sending to lobby server: "GETIP iridium[host]"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "ADDUSER parity US 38 SPADS v0.12.6", unmarshalled as:"ADDUSER,parity,US,38,SPADS v0.12.6"
20200426193413 - DEBUG    - [SpringLobbyInterface] Sending to lobby server: "GETUSERID parity"
20200426193413 - DEBUG    - [SpringLobbyInterface] Sending to lobby server: "GETIP parity"
20200426193413 - DEBUG    - [SpringLobbyInterface] Received from lobby server: "ADDUSER SLDB AU 85 SldbLi v0.2", unmarshalled as:"ADDUSER,SLDB,AU,85,SldbLi v0.2"
```

**Comment by Yaribz** [comment]
Thanks for the log, I think I found the problem, will try to fix.

**Comment by Yaribz** [comment]
Thanks for the log, I deleted it here because it contained a password hash (in LOGIN lobby command log) for which I didn't know if it was anonymized it or not.

Actually I need the "...skipping..." lines you removed, to know exactly which commands uberserver sent to SpringLobbyMonitor and find the inconsistency. Can you send me the original debug file by mail ? (my email can be found in SLDB and SPADS source files headers).

**Comment by Yaribz** [comment]
For now the only way I can explain your problem is if both following conditions are met at the same time:
- your SpringLobbyMonitor account doesn't have admin access rights on your uberserver instance (this is not a problem by itself, just note that SLDB would be much more efficient to catch smurfs accounts if SpringLobbyMonitor had admin rights)
- a broken lobby client (which doesn't update lobby ingame status when entering game) has been used with a rank 0 account to play a game on a SPADS autohost on your uberserver instance

These conditions should NOT lead to a fatal error at SpringLobbyMonitor side though, I will fix that.

**Comment by Yaribz** [comment]
I fixed the case described in my previous comment in commit 921a831. If the problem is still there for you after updating your slMonitor.pl file, it means it's something else. In this case I will need the "...skipping..." lines you removed from your log, to know exactly which commands uberserver sent to SpringLobbyMonitor and find the inconsistency (you can send me the original debug file by mail, my email can be found in SLDB and SPADS source files headers).

**Comment by Yaribz** [comment]
The full log you sent me confirms it's the case identified above, so I think the problem should be solved (you can disable the debug mode in your slMonitor.conf file).

FYI there might be something to fix at Chobby side also, because not a single CLIENTSTATUS command was received by your SpringLobbyMonitor instance for any "LuaLobby Chobby" user, as if Chobby didn't update its ingame status when entering a game.

**Comment by rosscosack** [comment]
Thanks very much
I will pass this info on to the chobby guys
I appreciate your help
Ross
